### ISSUE TITLE
Dismiss keyboard on NewViewController

### ISSUE THREAD

**Issue by gvillarg** [britkoala/pilot_this#1]

**Comment by ZaneH** [comment]
Latest <a href="https://github.com/britkoala/pilot_this/pull/4">pull request</a> fixes this issue:

<img src="http://i.imgur.com/5fGbFMS.gif" />

**Comment by yayoF** [comment]
Hey! Hi! Thanks! How/What do you use to generate that gif so easily?

**Comment by ZaneH** [comment]
Haha, glad you asked: https://gist.github.com/dergachev/4627207
Really handy tool!

**Comment by gvillarg** [comment]
Solved on commit #447096447042
